# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1526033215);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1526033335);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1526312293);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1526033095);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1526312413);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140916104755");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20140916104755");
user_pref("browser.startup.homepage_override.mstone", "31.1.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1525435305866");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1526312238210");
user_pref("datareporting.policy.firstRunTime", "1525348905865");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.firstPaint", 7566);
user_pref("datareporting.sessions.current.main", 2653);
user_pref("datareporting.sessions.current.sessionRestored", 8051);
user_pref("datareporting.sessions.current.startTime", "1526365417272");
user_pref("datareporting.sessions.current.totalTime", 35);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.1", "{\"s\":1526032849041,\"a\":149,\"t\":2751,\"c\":false,\"m\":2143,\"fp\":15086,\"sr\":15600}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1526062966949,\"a\":1,\"t\":25,\"c\":false,\"m\":2188,\"fp\":6718,\"sr\":7263}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1526312165631,\"a\":18,\"t\":204,\"c\":false,\"m\":3500,\"fp\":11145,\"sr\":12171}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.1.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1525280323000,\"rdfTime\":1410867943000}}}]");
user_pref("extensions.lastAppVersion", "31.1.0");
user_pref("extensions.lastPlatformVersion", "31.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140916104755");
user_pref("gecko.mstone", "31.1.0");
user_pref("idle.lastDailyNotification", 1526312420);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 25712);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1526365419);
user_pref("toolkit.telemetry.previousBuildID", "20140916104755");
